_merge = "deep"

languageCode = 'fr-fr'
title = 'DRH Minstère des affaires étrangères'

[module]
[[module.imports]]
path = 'github.com/disic/frago'

[outputs]
 home    = ["HTML","JSON"]

[params]
  organisation = "DRH Minstère des affaires étrangères"
  robots = "noindex, nofollow"
